import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../api/axios';
import { Loader2, Mail, CheckCircle, XCircle, Sparkles, MapPin, AlignLeft, ShieldCheck, Search } from 'lucide-react';
import toast from 'react-hot-toast';

const Matches = () => {
    const [matches, setMatches] = useState([]);
    const [loading, setLoading] = useState(true);

    const fetchMatches = async () => {
        try {
            const res = await api.get('/matching');
            setMatches(res.data.data);
        } catch (error) {
            toast.error("Failed to load matches");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchMatches();
    }, []);

    const handleAction = async (matchId, status) => {
        try {
            await api.patch(`/matching/${matchId}`, { status });
            toast.success(`Match successfully ${status}`);
            fetchMatches(); // refresh
        } catch (error) {
            toast.error("Failed to update match status");
        }
    }

    if (loading) return (
        <div className="min-h-[60vh] flex items-center justify-center bg-slate-50">
            <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
        </div>
    );

    return (
        <div className="bg-slate-50 min-h-screen py-10">
            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">
                <div className="mb-10 text-center sm:text-left">
                    <h1 className="text-3xl sm:text-4xl font-extrabold text-primary-900 tracking-tight mb-3">AI Matches</h1>
                    <p className="text-slate-600 text-lg max-w-2xl font-medium">Review potential matches generated by the semantic engine and securely arrange handoffs to reclaim your items.</p>
                </div>

                {matches.length === 0 ? (
                    <div className="bg-white border-2 border-dashed border-slate-200 p-12 text-center rounded-2xl shadow-sm">
                        <Sparkles className="w-10 h-10 text-slate-600 mx-auto mb-4" />
                        <p className="text-slate-500 font-bold tracking-widest uppercase text-sm">No AI matches found yet for your items.</p>
                    </div>
                ) : (
                    <div className="grid gap-6">
                        <AnimatePresence>
                            {matches.map((match, idx) => {
                                const scoreColor = match.scores.overall > 0.8 ? 'text-emerald-600 bg-emerald-50 border-emerald-200' : 'text-primary-600 bg-primary-50 border-primary-200';

                                return (
                                    <motion.div key={match._id}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: idx * 0.1 }}
                                        className="premium-card bg-white p-6 sm:p-8"
                                    >
                                        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 pb-6 border-b border-slate-100">
                                            <div className="flex items-center gap-4 mb-4 sm:mb-0">
                                                <div className={`w-14 h-14 rounded-xl border flex items-center justify-center ${scoreColor}`}>
                                                    <span className="text-xl font-extrabold">{(match.scores.overall * 100).toFixed(0)}</span>
                                                </div>
                                                <div>
                                                    <h3 className="text-xl font-bold text-primary-900">Match Probability</h3>
                                                    <p className="text-xs text-slate-500 uppercase tracking-widest font-bold mt-1">ID: {match._id.slice(-8)}</p>
                                                </div>
                                            </div>

                                            {match.status === 'potential' ? (
                                                <div className="flex items-center gap-3 w-full sm:w-auto">
                                                    <button onClick={() => handleAction(match._id, 'confirmed')} className="flex-1 sm:flex-none flex items-center justify-center gap-2 bg-zinc-900 border border-zinc-200 text-white hover:bg-green-600 text-slate-900 px-5 py-2.5 rounded-lg font-bold transition-all shadow-sm active:scale-95 outline-none focus-visible:ring-2 focus-visible:ring-accent-mint focus-visible:ring-offset-2">
                                                        <CheckCircle className="w-5 h-5" /> Claim Match
                                                    </button>
                                                    <button onClick={() => handleAction(match._id, 'rejected')} className="p-2.5 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-all border border-slate-200 hover:border-red-200 outline-none focus-visible:ring-2 focus-visible:ring-red-600" title="Reject Match">
                                                        <XCircle className="w-5 h-5" />
                                                    </button>
                                                </div>
                                            ) : (
                                                <div className={`px-4 py-2 rounded-lg text-xs font-bold uppercase tracking-widest border flex items-center gap-2 ${match.status === 'confirmed' ? 'bg-emerald-50 text-green-800 border-green-200' : 'bg-red-50 text-red-700 border-red-200'}`}>
                                                    {match.status === 'confirmed' ? <CheckCircle className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}
                                                    {match.status}
                                                </div>
                                            )}
                                        </div>

                                        <div className="grid md:grid-cols-2 gap-6">
                                            {/* Lost Report Card */}
                                            <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 relative overflow-hidden">
                                                <div className="absolute top-0 left-0 w-1.5 h-full bg-amber-400"></div>
                                                <div className="flex items-center gap-2 mb-4 text-amber-600">
                                                    <Search className="w-4 h-4" />
                                                    <span className="text-xs font-bold uppercase tracking-widest">Lost Report Context</span>
                                                </div>
                                                <p className="text-lg font-extrabold text-primary-900 mb-2 line-clamp-1">{match.lostReportId?.itemName || 'Unknown Item'}</p>
                                                <p className="text-sm text-slate-600 leading-relaxed min-h-[40px] line-clamp-2">{match.lostReportId?.description}</p>
                                                {match.status === 'confirmed' && (
                                                    <div className="flex items-center gap-2 mt-4 pt-4 border-t border-slate-200 text-slate-700 font-semibold text-sm">
                                                        <Mail className="w-4 h-4 text-primary-500" /> {match.lostReportId?.userId?.email || 'N/A'}
                                                    </div>
                                                )}
                                            </div>

                                            {/* Found Report Card */}
                                            <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 relative overflow-hidden">
                                                <div className="absolute top-0 left-0 w-1.5 h-full bg-zinc-900 border border-zinc-200 text-white"></div>
                                                <div className="flex items-center gap-2 mb-4 text-green-700">
                                                    <ShieldCheck className="w-4 h-4" />
                                                    <span className="text-xs font-bold uppercase tracking-widest">Found Report Context</span>
                                                </div>
                                                <p className="text-lg font-extrabold text-primary-900 mb-2 line-clamp-1">{match.foundReportId?.itemName || 'Unknown Item'}</p>
                                                <p className="text-sm text-slate-600 leading-relaxed min-h-[40px] line-clamp-2">{match.foundReportId?.description}</p>
                                                {match.status === 'confirmed' && (
                                                    <div className="flex items-center gap-2 mt-4 pt-4 border-t border-slate-200 text-slate-700 font-semibold text-sm">
                                                        <Mail className="w-4 h-4 text-primary-500" /> {match.foundReportId?.userId?.email || 'N/A'}
                                                    </div>
                                                )}
                                            </div>
                                        </div>

                                        <div className="mt-8 pt-6 border-t border-slate-100 flex flex-col items-start">
                                            <h4 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-3 flex items-center gap-2">
                                                <AlignLeft className="w-4 h-4" /> AI Similarity Metrics
                                            </h4>
                                            <div className="flex flex-wrap gap-2">
                                                {match.reasons?.map((reason, i) => (
                                                    <span key={i} className="px-3 py-1.5 bg-blue-50 text-primary-700 border border-blue-100 rounded-md text-xs font-semibold">
                                                        {reason}
                                                    </span>
                                                ))}
                                            </div>
                                        </div>
                                    </motion.div>
                                )
                            })}
                        </AnimatePresence>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Matches;
